services:

  postgres:
    image: postgres:16
    container_name: movemate-postgres

    environment:
      POSTGRES_DB: movemate
      POSTGRES_USER: movemate
      POSTGRES_PASSWORD: movemate

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movemate -d movemate"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: movemate-qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_data:/qdrant/storage


volumes:
  postgres_data:
  qdrant_data: